name: CI

on:
  push:
    branches:
      - main

jobs:
  build-python-ci-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    env:
      DOCKER_DRIVER: overlay2
      DOCKER_TLS_CERTDIR: "/certs"
      REGISTRY: ghcr.io
      IMAGE_NAME: talk-booking

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache Python virtual environment
      uses: actions/cache@v3
      with:
        path: services/talk_booking/.venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GITHUB_ACTOR }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        cd ci_cd/python/
        docker build -t $REGISTRY/${{ github.repository }}/$IMAGE_NAME:cicd-python3.11-slim .
        docker push $REGISTRY/${{ github.repository }}/$IMAGE_NAME:cicd-python3.11-slim
