name: CI

on:
  push:
    branches:
      - main

jobs:
  build-python-ci-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    env:
      DOCKER_DRIVER: overlay2
      DOCKER_TLS_CERTDIR: "/certs"
      REGISTRY: ghcr.io
      IMAGE_NAME: talk-booking

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ci_cd/python/
        push: true
        tags: ${{ env.IMAGE_NAME }}:latest
