name: CI

on:
  push:
    branches:
      - main

jobs:
  build-python-ci-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    env:
      DOCKER_DRIVER: overlay2
      DOCKER_TLS_CERTDIR: "/certs"
      REGISTRY: ghcr.io
      IMAGE_NAME: talk-booking

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache Python virtual environment
      uses: actions/cache@v3
      with:
        path: services/talk_booking/.venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Log in to the container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ci_cd/python/
        file: ci_cd/python/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cicd-python3.11-slim
