name: DOcker Image CI for GHCR

# manually trigger the workflow
on:
  push:
    branches:
      - dev

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push the Image
        run: |
          docker login --username ${{ github.actor }} --password ${{ secrets.GH_PAT }}
          docker build --tag ghcr.io/${{ github.actor }}/talk-booking:cicd-python3.11-slim ci_cd/python/
          docker push ghcr.io/${{ github.actor }}/talk-booking:cicd-python3.11-slim
